apiVersion: v1
kind: Pod
metadata:
  name: example-container
spec:
  securityContext:
    runAsUser: 269394
    runAsGroup: 1132
  containers:
    - name: example-container
      image: ghcr.io/isuruariyarathne97/data-622-225:main
      resources:
        requests:
          memory: "16Gi"
          cpu: "8"
        limits:
          memory: "24Gi"
          cpu: "16"
      volumeMounts:
      - name: home
        mountPath: "/app"
      command: ["/bin/sh", "-c"]
      args:
        - |
          docker pull webrecorder/browsertrix-crawler
          docker run -v /app/crawls:/crawls/ -it webrecorder/browsertrix-crawler crawl \
          --url [URL] --generateWACZ --text --collection test
      stdin: true
      tty: true
  volumes:
  - name: home
    nfs:
      server: 128.239.56.166
      path: /sciclone/home/iahewababarand/repos/data-622-225
